// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaOdHy5Pu176V6brvr-2XlLhoMgIyJroc',
    appId: '1:194112293877:web:ee5ed4dda00e19d754eebc',
    messagingSenderId: '194112293877',
    projectId: 'starx-429cb',
    authDomain: 'starx-429cb.firebaseapp.com',
    storageBucket: 'starx-429cb.appspot.com',
    measurementId: 'G-R513M7KNJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPh3o8aSXZl5EW5y6zgudNE-A8TxKtjwo',
    appId: '1:194112293877:android:aab957d96c1cb6a254eebc',
    messagingSenderId: '194112293877',
    projectId: 'starx-429cb',
    storageBucket: 'starx-429cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa43ImaZgmFPHQCdMvaLEXG4pBzmHRfq8',
    appId: '1:194112293877:ios:e356d36c87f6f92d54eebc',
    messagingSenderId: '194112293877',
    projectId: 'starx-429cb',
    storageBucket: 'starx-429cb.appspot.com',
    iosBundleId: 'com.example.starx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa43ImaZgmFPHQCdMvaLEXG4pBzmHRfq8',
    appId: '1:194112293877:ios:e356d36c87f6f92d54eebc',
    messagingSenderId: '194112293877',
    projectId: 'starx-429cb',
    storageBucket: 'starx-429cb.appspot.com',
    iosBundleId: 'com.example.starx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaOdHy5Pu176V6brvr-2XlLhoMgIyJroc',
    appId: '1:194112293877:web:6f4d2b2d7c5ba72c54eebc',
    messagingSenderId: '194112293877',
    projectId: 'starx-429cb',
    authDomain: 'starx-429cb.firebaseapp.com',
    storageBucket: 'starx-429cb.appspot.com',
    measurementId: 'G-QH6JEHS7MM',
  );
}
